Sh empty folder
CertifaiAI/classifai pull request #226
Opened 2020-11-19 09:28 UTC by toh-sie-hung

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #223

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

2020-11-19 09:31 UTC, toh-sie-hung commented
Fixes the import empty folder problem. Once user import empty folder, the screen will back to labelling tool screen. Nothing new image will add and wont have message pop up. Able work on my laptop.

2020-11-19 14:29 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
> +            {
need to remove the println command which is suppose for debugging @toh-sie-hung 
else in the long run the command prompt output will have random messages.

2020-11-19 14:33 UTC, codenamewei requested changes

2020-11-19 14:33 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/selector/annotation/ToolFolderSelector.java
> +                            {
these operation happens in `ImageHandler.processFolder(projectID, rootFolder);` too

running it two times will cause the running time to massively increase, recommend to keep this file as how it was 

@toh-sie-hung

2020-11-19 14:39 UTC, codenamewei commented
Advise changing in [ImageHandler.java L 258](https://github.com/CertifaiAI/classifai/blob/sh_empty_folder/classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java#L258)

```
if(filesCollection.isEmpty())
        {
            loader.reset(FileSystemStatus.WINDOW_CLOSE_DATABASE_NOT_UPDATED);
            return;
        }
```

![Screenshot 2020-11-19 223715](https://user-images.githubusercontent.com/33477318/99680306-e0925400-2ab7-11eb-8d47-4ff367429e7d.jpg)

2020-11-20 01:28 UTC, toh-sie-hung commented on classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
> +            {
sorry, forget to remove it. Thx for checking

2020-11-20 01:32 UTC, toh-sie-hung commented
okay, noted.

2020-11-20 01:50 UTC, toh-sie-hung commented
I just moved the code from toolfolderselector file to imagehandle file

2020-11-22 16:05 UTC, codenamewei approved these changes
Works well now.

2020-11-22 16:05 UTC, merged