Multi-language support, Shortcut key information
CertifaiAI/classifai pull request #311
Opened 2021-02-18 02:44 UTC by amalsyahmi-certifai

# Description

Changes on front-end:
- Add Malay and Chinese language support.
- Add shortcut key information dialog.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tested on?

- [ ] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

2021-02-18 04:02 UTC, codenamewei requested changes
there's remaining english phrases here and there which i believe daniel has highlight to you

2021-02-19 03:56 UTC, amalsyahmi-certifai reviewed
Done translate for loading screens, alert dialog, file upload button, tooltips

2021-02-22 01:14 UTC, codenamewei commented
> Done translate for loading screens, alert dialog, file upload button, tooltips

perfect. thanks

2021-02-22 01:14 UTC, codenamewei approved these changes

2021-02-22 01:14 UTC, merged