Check sanity of json file when import
CertifaiAI/classifai pull request #330
Opened 2021-03-23 07:37 UTC by devenyantis

# Description

Check json file when importing project. 

- Check if version of installed classifai is the same with tools from json file. If not, popup warning window.
- Check if json file has all the keys required. If no, popup error windows and skip project import. 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged

2021-03-23 14:01 UTC, codenamewei commented
@devenyantis 
running from terminal with `./startClassifai.sh` or using editor as shown as screenshot below resulted in _null_ in the _tool_version_

let me know if need more info to replicate what im seeing

<img width="740" alt="Screenshot 2021-03-23 at 9 59 46 PM" src="https://user-images.githubusercontent.com/33477318/112158569-41c36300-8c23-11eb-9c19-42cb870d349c.png">

2021-03-23 14:11 UTC, codenamewei requested changes

2021-03-23 14:11 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/action/ActionConfig.java
> +    @Getter private static final String tool_version = ActionConfig.class.getPackage().getImplementationVersion();
camel case

2021-03-23 14:11 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/action/ActionConfig.java
> +    @Getter private static final List<String> keys = Arrays.asList(
most of these variables are in https://github.com/CertifaiAI/classifai/blob/deven_checkjsonimport/classifai-core/src/main/java/ai/classifai/util/ParamConfig.java

try to call these parameters to prevent hard code

also if the variable doesnt exist, feel free to define in ActionConfig class as a variable and refer to it
for example
- tool
- tool_version
- updated_date
(these can be put in the ActionConfig class instead of ParamConfig class because i foresee only import export using these)

2021-03-23 14:11 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/action/ProjectImport.java
> +            if(!checkJsonKeys(inputJsonObject))
there's no boolean coming out from checkToolVersion function to decide whether to continue the operation of not

can this be structure into the format of 

`if(!checkToolVersion(...) || !(checkJsonKeys(...))
`

2021-03-24 03:47 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/ProjectImport.java
> +            if(!checkJsonKeys(inputJsonObject))
My reasoning is because we might change the version of tools when adding other functionality, but no change in the functionality of import/export. So, it will give out warning only message and not error.

2021-03-24 03:50 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/action/ProjectImport.java
> +            if(!checkJsonKeys(inputJsonObject))
ah okay..then can go with your logics

this makes me wonder did we already covered the use case of 
importing a total random json file which is not for this purpose of import/export...

2021-03-24 07:08 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/ProjectImport.java
> +            if(!checkJsonKeys(inputJsonObject))
Yes. So, the checking work in these order
1. Check if tool, tool_version, update_date key exist. And check if tool is classifai. If not, popup error, skip import
2. Check tool version. Only popup warnings. Still proceed to import
3. Check available keys. Make sure all needed keys available. If any is missing, popup error, skip import

2021-03-25 03:26 UTC, codenamewei approved these changes
Looking good, tested the logic and its working too..

If you would just solve this [code smell ](https://sonarcloud.io/project/issues?id=CertifaiAI_classifai&open=AXheBfRHeE3ewwtgrtyD&pullRequest=330&resolved=false&types=CODE_SMELL) and merge it . 
(we can neglect the other two code smells)

also reminder to practice the new commit practice which you can see in classifai_dev_team channel . thanks deven.

2021-03-25 03:47 UTC, merged