Improve image validation time
CertifaiAI/classifai pull request #339
Opened 2021-04-05 12:35 UTC by YCCertifai

# Description
During image import, there's a validation process of import images.
Current method used is try to **read the image files**, finding the width and height...
https://github.com/CertifaiAI/classifai/blob/main/classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java#L250-L274

Method proposed to shorten the validation time is by **reading the metadata** of images instead of reading the whole image.

Amount of time reduce:
3500 images: 10 mins -> 20 secs 
this [folder](https://drive.google.com/file/d/1R5jaaqlCWr3StE0KH1hPsL79s0AW_vcg/view?usp=sharing) contains the tested images.
[fake images](https://drive.google.com/file/d/1F_OMJH__bHZUcRpptxytfnyzynGNaH-S/view?usp=sharing) are also provided to test on ability to filter invalid files.

## Type of change
performance improvement.

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tested on?

- [ ] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

2021-04-05 15:16 UTC, codenamewei commented
@YCCertifai 
**question:** 
1. there are getWidth(Metadata metadata) and getWidth(BufferedImage img, int orientation)
What are the conditions you will use getWidth(Metadata metadata) ? or is it rather for validation purpose on line https://github.com/CertifaiAI/classifai/blob/b45fd8a60c1f7c48ac2b222cecaa471962c30856/classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java#L262?

2. PR goes to main branch. Is there audience waiting for this fix?

**comment:**
Capital first letter when write commit message
https://skymind.slack.com/archives/G0182D7GS9W/p1616633494005100

<img width="368" alt="Screenshot 2021-04-05 at 10 42 43 PM" src="https://user-images.githubusercontent.com/33477318/113589960-9c69af80-9664-11eb-8b0d-7cac82bd57a1.png">

2021-04-06 01:14 UTC, YCCertifai commented
1. getWidth/Height(Metadata metadata) are only used for validation purpose. getWidth/Height(BufferedImage img, int orientation) are used for determine height and weight of images by taking account into orientation.
2. Internal staffs that using it for agift.

Thanks for reminding of commit style, will take note of it.

2021-04-06 01:45 UTC, codenamewei requested changes

2021-04-06 01:45 UTC, codenamewei commented on .gitignore
> +classifai-distro
classifai-distro is obsolete, current repository dont have it already

2021-04-06 01:45 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
> +            if((getWidth(metadata) > ImageFileType.getMaxWidth()) || (getHeight(metadata) > ImageFileType.getMaxHeight()))
since its for this validation purpose 

suggest changing getWidth(metadata) & getHeight(metadata) 
to 

```
if(isImageSizeInRange(metadata)) 
{
}
```

2021-04-06 01:45 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
> +    private static int getHeight(Metadata metadata) throws NotSupportedImageTypeError, MetadataException
error can be throw in the one function 

```
private static boolean isImageSizeInRange(metadata)
{
       try
       {
       }
       catch(Exception e)
       {
       
}

```

2021-04-06 03:14 UTC, YCCertifai commented
@codenamewei noted
will make changes accordingly

2021-04-21 09:44 UTC, YCCertifai commented
Not releasing for V1 anymore

2021-04-21 09:44 UTC, closed without merging