Export config file & data as zip file
CertifaiAI/classifai pull request #345
Opened 2021-04-13 02:08 UTC by devenyantis

# Description

User is able to choose whether to

- export config file only
- export config file with data (zip together)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update

# Tested on?

- [X] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged

2021-04-13 09:36 UTC, codenamewei commented
A few thing I realised when runnning it

- ![Screenshot 2021-04-13 at 5 19 06 PM](https://user-images.githubusercontent.com/33477318/114530120-3b9e3080-9c7d-11eb-8f0b-4004a93413fa.png)

Capital should be better for consistency 

- https://gist.github.com/codenamewei/76a5aaa2cfdf3d3d0281f74fe310582d

Thread is blocked when the above window stay opens for 15 seconds and above

However the same scenario did not happen when the project folder stay open ...
![Screenshot 2021-04-13 at 5 22 08 PM](https://user-images.githubusercontent.com/33477318/114530276-5ffa0d00-9c7d-11eb-9ad0-a769d36a4c21.png)

or even this pop up message below stay open for more than 15 seconds
![Screenshot 2021-04-13 at 5 32 38 PM](https://user-images.githubusercontent.com/33477318/114531368-6b016d00-9c7e-11eb-8469-5d116bd29826.png)



as much of it doesnt causing error for now , would like to relook into to 
(1) not possibly blocking the thread and consuming computation power
(2) spamming the log file which hinders effective debugging

@devenyantis

2021-04-13 09:37 UTC, codenamewei requested changes

2021-04-13 09:37 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/action/ActionOps.java
> +    public static ExportType getExportType(String export_type_str)
export_type_str to CamelCase thanks

2021-04-15 06:32 UTC, devenyantis commented
@codenamewei 

Merged PR for choose export options

![Capture1](https://user-images.githubusercontent.com/69179469/114824255-38c74b00-9df7-11eb-98e8-ca497a211f39.PNG)

2021-04-20 02:59 UTC, codenamewei commented
@amalsyahmi-certifai @devenyantis 
The layout need changes ....
i find the **cancel** button come first is wacky

suggest layout like below..

for those who decide not to perform any operation can click close button to exit

The button **Config File** & **Zip File (With Data)** have to be same size too
hence the two layouts for suggestion
alternatively the phrase **(With Data)** can be made with a smaller font too (because its of extra note)

![Image from iOS (2)](https://user-images.githubusercontent.com/33477318/115330798-587bbc00-a1c7-11eb-8e34-a96697ac2110.jpg)
![Image from iOS (1)](https://user-images.githubusercontent.com/33477318/115330803-5a457f80-a1c7-11eb-940c-a4b3f5cf5bf9.jpg)

2021-04-20 02:59 UTC, codenamewei requested changes
As per comment

2021-04-20 03:08 UTC, devenyantis commented
> @amalsyahmi-certifai @devenyantis
> The layout need changes ....
> i find the **cancel** button come first is wacky
> 
> suggest layout like below..
> 
> for those who decide not to perform any operation can click close button to exit
> 
> The button **Config File** & **Zip File (With Data)** have to be same size too
> hence the two layouts for suggestion
> alternatively the phrase **(With Data)** can be made with a smaller font too (because its of extra note)
> 
> ![Image from iOS (2)](https://user-images.githubusercontent.com/33477318/115330798-587bbc00-a1c7-11eb-8e34-a96697ac2110.jpg)
> ![Image from iOS (1)](https://user-images.githubusercontent.com/33477318/115330803-5a457f80-a1c7-11eb-940c-a4b3f5cf5bf9.jpg)

@amalsyahmi-certifai I'm fine with the first one. So, the size won't be too big. 
And maybe the `close` button can be smaller than the options.

2021-04-20 03:10 UTC, codenamewei commented
> @amalsyahmi-certifai I'm fine with the first one. So, the size won't be too big.
> And maybe the `close` button can be smaller than the options.

yes im onboard on the smaller close button too...thanks guys

2021-04-20 03:51 UTC, amalsyahmi-certifai commented
@codenamewei @devenyantis , is this good?
![image](https://user-images.githubusercontent.com/76939137/115334816-a1833e80-a1ce-11eb-856c-b5ba261e3e9a.png)

2021-04-20 05:17 UTC, amalsyahmi-certifai commented
@codenamewei @devenyantis 

Design proposed by @codenamewei . The 'Config File' text aligns with 'Zip File' in the second button. For me, I like the previous design ('Config File' text aligns center in the button). What do you think?

![image](https://user-images.githubusercontent.com/76939137/115340671-b87b5e00-a1d9-11eb-9c5e-a4ef4a8cc090.png)

2021-04-20 05:28 UTC, BobbyLCW commented
I would like to suggest the cancel button take away. make it a cross (x) on top right corner (size smaller). At the same time, enable click on blank space can exit this interface.

2021-04-20 06:27 UTC, codenamewei commented
> I would like to suggest the cancel button take away. make it a cross (x) on top right corner (size smaller). At the same time, enable click on blank space can exit this interface.

@amalsyahmi-certifai Yeah , alignment on first one is better

can you also check out Bobby comments?
the x on the top is align with classifai other interface
![Screenshot 2021-04-20 at 2 25 32 PM](https://user-images.githubusercontent.com/33477318/115347775-65f36f00-a1e4-11eb-8652-502f05605e61.png)

, which failed to cross my mind till now


also the click on blank space to exit too, the same thing can implement on this shortcut key page

2021-04-20 07:51 UTC, amalsyahmi-certifai commented
@codenamewei @BobbyLCW 
Thank you for the suggestions.
I will proceed with the first design first. For cross on top right corner and click outside of the modal to close, I will do in the next PR.

2021-04-21 05:30 UTC, codenamewei approved these changes
👍

2021-04-21 05:30 UTC, merged