:memo: Update readme.md to the same as main
CertifaiAI/classifai pull request #379
Opened 2021-05-25 10:26 UTC by YCCertifai

# Description

Update readme.md to the same as main as now this is set at the default branch.
People can download the latest v1.2.0 built version from the readme page.

2021-05-25 12:50 UTC, codenamewei requested changes

2021-05-25 12:50 UTC, codenamewei commented on readme.md
> +<img src="metadata/click-here-button.png" width="90"/>
click-here-button.png is not available in neither [v2_alpha ](https://github.com/CertifaiAI/classifai/tree/v2_alpha/metadata)or [v2a_sum_readme_update](https://github.com/CertifaiAI/classifai/tree/v2a_sum_readme_update/metadata)

2021-05-26 06:57 UTC, YCCertifai commented on readme.md
> +<img src="metadata/click-here-button.png" width="90"/>
ah.. my bad...
wasn't aware of that...
it's added now

2021-05-26 07:11 UTC, codenamewei approved these changes
👍

2021-05-26 07:11 UTC, merged