Code of Conduct and Contributing draft
CertifaiAI/classifai pull request #413
Opened 2021-06-15 02:32 UTC by ken479

First draft of code of conduct and contributing for review.

2021-06-15 02:47 UTC, codenamewei requested changes

2021-06-15 02:47 UTC, codenamewei commented on CodeofConduct.md
> +This Code of Conduct applies to all content in Certifai and Classifai github, within all project spaces, and it also applies when an individual is representing Cerifai or Classifai, the project or it
typo -> Cerifai

2021-06-15 02:47 UTC, codenamewei commented on Contributing.md
> +* [Contribution Guildeline](#contribution-guideline)
typo -> Guildeline

2021-06-15 02:47 UTC, codenamewei commented on Contributing.md
> +You did it! Thank you so much for your contribution. We are so appreciated. Kindly wait for further notice while we checking you codes. We will get back to you soon through email or comment at github
either below will works
- while we are checking 
- while we check

2021-06-15 02:47 UTC, YCCertifai commented on CodeofConduct.md
> +In the interest in fostering an open and welcoming environment, we as contributors and maintainers pledge to make participation in our project and our community a harassment-free experience for every
typo for ethnicity

2021-06-15 02:59 UTC, ken479 commented on CodeofConduct.md
> +This Code of Conduct applies to all content in Certifai and Classifai github, within all project spaces, and it also applies when an individual is representing Cerifai or Classifai, the project or it
@codenamewei Thank you chia wei. Will correct it.

2021-06-15 02:59 UTC, ken479 commented on Contributing.md
> +* [Contribution Guildeline](#contribution-guideline)
@codenamewei Thank you chia wei. Will correct it.

2021-06-15 02:59 UTC, ken479 commented on Contributing.md
> +You did it! Thank you so much for your contribution. We are so appreciated. Kindly wait for further notice while we checking you codes. We will get back to you soon through email or comment at github
@codenamewei Thank you chia wei. Will correct it.

2021-06-15 03:00 UTC, ken479 commented on CodeofConduct.md
> +In the interest in fostering an open and welcoming environment, we as contributors and maintainers pledge to make participation in our project and our community a harassment-free experience for every
@YCCertifai Thank you. will correct it.

2021-06-15 04:48 UTC, codenamewei approved these changes
ok from my side

2021-06-16 02:58 UTC, YCCertifai approved these changes
looks good to me too

2021-06-16 02:59 UTC, merged