Renaming image from work space
CertifaiAI/classifai pull request #439
Opened 2021-06-24 09:30 UTC by devenyantis

# Description

Users are able to rename image.

Tested for data with and without child directory.

Frontend PR: https://github.com/CertifaiAI/classifai/pull/438

Will update documentation, changelog and gitbook api docs if accepted.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (Non-breaking change which fixes an issue)
- [X] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [X] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

2021-06-24 10:17 UTC, devenyantis commented
@codenamewei 

Tested with the frontend PR

How I test

1. Create new branch (dummy branch for testing only) based on this branch
2. Merge the frontend auto PR https://github.com/CertifaiAI/classifai/pull/438
3. Perform functions test.

2021-06-28 00:45 UTC, codenamewei commented
@devenyantis thanks for the guided pointers to test on this PR

im seeing the full path in the edit image 

<img width="584" alt="Screenshot 2021-06-28 at 8 42 23 AM" src="https://user-images.githubusercontent.com/33477318/123564704-f3f36380-d7ec-11eb-91da-f1a543880f50.png">

is that intentional? 
`path: /Users/chiawei/Desktop/classifai_dataset/Agriculture-sample-12345/Agriculture-sample-123/agriculture-sample-123456/animal11`

changing other than image name will resulted in following 

<img width="529" alt="Screenshot 2021-06-28 at 8 44 02 AM" src="https://user-images.githubusercontent.com/33477318/123564736-18e7d680-d7ed-11eb-8635-2cad4f804e9e.png">

2021-06-28 00:57 UTC, codenamewei requested changes

2021-06-28 00:57 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/action/RenameProjectData.java
> +package ai.classifai.action;
license header

2021-06-28 00:57 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/action/RenameProjectData.java
> +
simple documentation on what the class about and author name with @author

2021-06-28 00:57 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/action/RenameProjectData.java
> +            message.reply(ReplyHandler.reportUserDefinedError("Name exists"));
can we get more detailed debug messages over here? 

<img width="567" alt="Screenshot 2021-06-28 at 8 53 03 AM" src="https://user-images.githubusercontent.com/33477318/123565099-45502280-d7ee-11eb-971e-77a5f2e9b590.png">


for example indicating what is the name of the file that exist

this helps in debugging by looking back the log file if needed

2021-06-28 00:57 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/action/RenameProjectData.java
> +            message.reply(ReplyHandler.reportUserDefinedError("Fail to rename file"));
same here

2021-06-28 00:57 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/action/RenameProjectData.java
> +                                "Fail to update filename in database"));
same here

2021-06-28 00:57 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/action/RenameProjectData.java
> +        String newDataPathFName = newFilename.substring(newFilename.lastIndexOf(File.separator) + 1, newFilename.lastIndexOf("."));
not very bothering 
but im seeing three naming of "file name"
as 
- FileName
- Filename
- FName (understand this is used because the variable name is long) 

im okay with a mix of FName and FileName / Filename 
lets keep it consistent either using FileName, Filename

2021-06-28 01:12 UTC, codenamewei commented
@devenyantis i've merge working frontend (faris_auto_pr) to this branch, do a fresh pull if needed. thanks

2021-06-28 01:53 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/RenameProjectData.java
> +        String newDataPathFName = newFilename.substring(newFilename.lastIndexOf(File.separator) + 1, newFilename.lastIndexOf("."));
Will use FileName

2021-06-28 02:00 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/RenameProjectData.java
> +            message.reply(ReplyHandler.reportUserDefinedError("Fail to rename file"));
This is depending on return value from renameTo which comes from File. Will raise Null pointer exception when fail. Printing the exact error is not possible.

2021-06-28 02:03 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/RenameProjectData.java
> +                                "Fail to update filename in database"));
loggin the query. jdbc will print exception and traceback if fail

2021-06-28 02:03 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/RenameProjectData.java
> +            message.reply(ReplyHandler.reportUserDefinedError("Name exists"));
logging the filename

2021-06-28 02:21 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/action/RenameProjectData.java
> +            message.reply(ReplyHandler.reportUserDefinedError("Fail to rename file"));
okay

2021-06-28 03:03 UTC, devenyantis commented
> @devenyantis thanks for the guided pointers to test on this PR
> 
> im seeing the full path in the edit image
> 
> <img alt="Screenshot 2021-06-28 at 8 42 23 AM" width="584" src="https://user-images.githubusercontent.com/33477318/123564704-f3f36380-d7ec-11eb-91da-f1a543880f50.png">
> 
> is that intentional?
> `path: /Users/chiawei/Desktop/classifai_dataset/Agriculture-sample-12345/Agriculture-sample-123/agriculture-sample-123456/animal11`
> 
> changing other than image name will resulted in following
> 
> <img alt="Screenshot 2021-06-28 at 8 44 02 AM" width="529" src="https://user-images.githubusercontent.com/33477318/123564736-18e7d680-d7ed-11eb-8635-2cad4f804e9e.png">

@codenamewei 

Does the image name on the data list also show the full path?

2021-06-28 03:10 UTC, codenamewei commented
> > @devenyantis thanks for the guided pointers to test on this PR
> > im seeing the full path in the edit image
> > <img alt="Screenshot 2021-06-28 at 8 42 23 AM" width="584" src="https://user-images.githubusercontent.com/33477318/123564704-f3f36380-d7ec-11eb-91da-f1a543880f50.png">
> > is that intentional?
> > `path: /Users/chiawei/Desktop/classifai_dataset/Agriculture-sample-12345/Agriculture-sample-123/agriculture-sample-123456/animal11`
> > changing other than image name will resulted in following
> > <img alt="Screenshot 2021-06-28 at 8 44 02 AM" width="529" src="https://user-images.githubusercontent.com/33477318/123564736-18e7d680-d7ed-11eb-8635-2cad4f804e9e.png">
> 
> @codenamewei
> 
> Does the image name on the data list also show the full path?

@devenyantis 
on the right panel, only image name itself being show (without path) 

i suggest whipping up an ubuntu vm to check that out....normally when things is seen in mac, same scenario happens in ubuntu too

2021-06-29 02:46 UTC, codenamewei commented
not able to do pr merge due to how there's conflicts , probably due how the auto pr is based on v2_alpha
webroot is directly updated in a commit to this branch

do a pull thanks, @devenyantis

2021-06-29 11:01 UTC, codenamewei approved these changes

2021-06-29 11:04 UTC, merged

2021-06-29 11:12 UTC, codenamewei commented
@devenyantis 
not too sure do you want to put items below in this PR, only realised after i merged.
do work on updating documentation, changelog and gitbook api docs thanks!

2021-06-29 11:34 UTC, devenyantis commented
> @devenyantis
> not too sure do you want to put items below in this PR, only realised after i merged.
> do work on updating documentation, changelog and gitbook api docs accordingly thanks!

Sure. Will update the change