♻️ Refactor code on ImageData, ImageHandler and Integrate OpenCV Java
CertifaiAI/classifai pull request #462
Opened 2021-07-05 15:12 UTC by ken479

# Description

Integrated OpenCV Java into Classifai to support webp image and other image types. Refactor some codes from ImageHandler and make ImageData as abstract class to provide a layer of screening on Image types and make ImageData more organized to be used in ImageHandler. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (Non-breaking change which fixes an issue)
- [ ] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [x] Windows  
- [x] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

2021-07-05 15:53 UTC, codenamewei requested changes

2021-07-05 15:53 UTC, codenamewei commented on pom.xml
> +                <version>4.5.1-2</version>
dependency define in [properties](https://github.com/CertifaiAI/classifai/blob/08cafc2bb72e728290182a7f65fb6605d2f8f567/pom.xml#L72-L101)
and call 
it to here example
```
<dependency>
                <groupId>org.openpnp</groupId>
                <artifactId>opencv</artifactId>
                <version>{opencv.version}</version>
</dependency>
```

2021-07-05 15:53 UTC, codenamewei commented on classifai-core/pom.xml
> +            <version>4.5.1-2</version>
in submodule pom.xml no need to define version
it will find back the version in the root pom.xml

2021-07-06 01:06 UTC, ken479 commented on pom.xml
> +                <version>4.5.1-2</version>
Thank you @codenamewei for the suggestion

2021-07-06 01:06 UTC, ken479 commented on classifai-core/pom.xml
> +            <version>4.5.1-2</version>
Noted. will remove it.

2021-07-08 02:06 UTC, YCCertifai requested changes

2021-07-08 02:06 UTC, YCCertifai commented on classifai-core/src/main/java/ai/classifai/data/type/image/ImageData.java
> +            } else {
need to screen out animated webp images from here too, currently animated webp image will be allowed, and create errors in application.
![image](https://user-images.githubusercontent.com/76682536/124850603-85c05500-dfd3-11eb-9871-dc3afe0371dc.png)

2021-07-08 02:06 UTC, YCCertifai commented on classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
> +//            imgData = ImageHandler.getThumbNail(img);
need to remove the commented unused code, unless there is a special purpose for it

2021-07-08 04:48 UTC, closed without merging