♻️ Refactor code on Image Handling and Integrate OpenCV Java
CertifaiAI/classifai pull request #464
Opened 2021-07-08 03:43 UTC by ken479

# Description

Integrated OpenCV Java into Classifai to support Webp image and other image types. Add in WebpImageData file. Add in "webp" in allowed file types and base64Header in ImageFileType. Refactor codes in ImageHandler and make ImageData as an abstract class to provide a layer of screening on Image types and make ImageData more organized to be used in ImageHandler. 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (Non-breaking change which fixes an issue)
- [x] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [x] Windows  
- [x] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

2021-07-08 04:14 UTC, codenamewei requested changes
hi @ken479 

also look through these and try to solve most of it 
https://sonarcloud.io/project/issues?id=CertifaiAI_classifai&pullRequest=464&resolved=false&types=CODE_SMELL

2021-07-08 04:18 UTC, ken479 commented
> hi @ken479
> 
> also look through these and try to solve most of it
> https://sonarcloud.io/project/issues?id=CertifaiAI_classifai&pullRequest=464&resolved=false&types=CODE_SMELL

Hi @codenamewei , I will look into it and solve it.

2021-07-08 04:26 UTC, YCCertifai requested changes
These are the same as the #462, @ken479 you can proceed to close that pr. Thanks!

2021-07-08 04:26 UTC, YCCertifai commented on classifai-core/src/main/java/ai/classifai/data/type/image/ImageData.java
> +            } else {
need to screen out animated webp images from here too, currently animated webp image will be allowed, and create errors in application.
![](https://user-images.githubusercontent.com/76682536/124850603-85c05500-dfd3-11eb-9871-dc3afe0371dc.png)

2021-07-08 04:26 UTC, YCCertifai commented on classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
> +            angle = Math.PI/2;
for the purpose of clean & reusable code, this could be a method in ImageData.
just like getOrientation(), you can have a method call getRotationAngle() which return a double.

2021-07-08 04:26 UTC, YCCertifai commented on classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
> +//            imgData = ImageHandler.getThumbNail(img);
need to remove the commented unused code, unless there is a special purpose for it

2021-07-08 04:46 UTC, ken479 commented
> These are the same as the #462, @ken479 you can proceed to close that pr. Thanks!

Noted. Thanks.

2021-07-08 04:47 UTC, ken479 commented on classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
> +//            imgData = ImageHandler.getThumbNail(img);
@YCCertifai Thank you for the comments, I will improve the coding accordingly.

2021-07-08 10:12 UTC, YCCertifai approved these changes

2021-07-09 00:41 UTC, codenamewei requested changes

2021-07-09 00:41 UTC, codenamewei commented on classifai-core/src/main/java/ai/classifai/data/type/image/WebpImageData.java
> +package ai.classifai.data.type.image;
add license header

and short description like other class file 
Example [1](https://github.com/CertifaiAI/classifai/blob/ken_ImageHandling/classifai-core/src/main/java/ai/classifai/data/type/image/JpegImageData.java) [2](https://github.com/CertifaiAI/classifai/blob/ken_ImageHandling/classifai-core/src/main/java/ai/classifai/action/FileGenerator.java)

The year license header for this file will just be 2021 because its created this year

2021-07-09 00:44 UTC, ken479 commented on classifai-core/src/main/java/ai/classifai/data/type/image/WebpImageData.java
> +package ai.classifai.data.type.image;
Hi @codenamewei, thank you for the comment, I will add the information.

2021-07-09 01:19 UTC, codenamewei approved these changes

2021-07-09 02:00 UTC, merged