♻️ Add database facade
CertifaiAI/classifai pull request #502
Opened 2021-09-03 03:58 UTC by devenyantis

# Description

Adding database facade

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (Non-breaking change which fixes an issue)
- [ ] New feature (Non-breaking change which adds functionality)
- [X] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [X] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

2021-09-03 06:14 UTC, ken479 approved these changes

2021-09-03 07:58 UTC, treo requested changes

2021-09-03 07:58 UTC, treo commented on classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
> +               HTTPResponseHandler.configureOK(context, future.result());
this looks odd, shouldn't it be enough to pass `result` here? and other similar places?

2021-09-03 07:58 UTC, treo commented on classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
> +           }
I see this pattern appearing quite often, it probably makes sense to have something that you can instead call like:
`ReplyHandler.sendResultOrError(future, "Failure in getting image source.")`

2021-09-03 07:58 UTC, treo commented on classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
> +                        ReplyHandler.reportUserDefinedError(errorMessage));
As you are handling the error message in the same way, it makes more sense to chain those futures instead of nesting them like that.

2021-09-06 03:36 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
> +               HTTPResponseHandler.configureOK(context, future.result());
You mean not having the future.onComplete ? just pass the future.result() directly?

2021-09-06 03:36 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
> +           }
Noted

2021-09-06 03:36 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
> +                        ReplyHandler.reportUserDefinedError(errorMessage));
Noted

2021-09-06 03:43 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
> +           }
Thinking of something like this
```
    public static void sendResult(RoutingContext context, Future<JsonObject> future, String errorMessage) {
        future.onComplete(result -> {
            if(result.succeeded()) {
                HTTPResponseHandler.configureOK(context, result.result());
            } else {
                HTTPResponseHandler.configureOK(context, ReplyHandler.reportUserDefinedError(errorMessage));
            }
        });
    }
```

And using it
```
Future<JsonObject> future = portfolioDB.getProjectMetadata(loader.getProjectId());
ReplyHandler.sendResult(context, future, "Failed to retrieve metadata for project " + projectName);
```

2021-09-06 06:05 UTC, treo commented on classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
> +               HTTPResponseHandler.configureOK(context, future.result());
I mean instead of using `future.result()`, you should be able to use `result` directly, as you are getting it passed into your lambda anyway.

2021-09-06 06:05 UTC, treo commented on classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
> +           }
Looks reasonable.

2021-09-06 06:08 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
> +               HTTPResponseHandler.configureOK(context, future.result());
Ahh yes. changing that as well.

2021-09-07 07:52 UTC, treo requested changes
Mostly good, just a few more comments.

2021-09-07 07:52 UTC, treo commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
> +    }
If I understand this code correctly, `runPortfolioQuery` can be implemented as `return runAnnotationQuery(msg, action, queue)`.

2021-09-07 07:52 UTC, treo commented on classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
> +                log.info("Failure in updating database for " + loader.getAnnotationType() + " project: " + loader.getProjectName());
This looks odd, the success case isn't handled anymore?

2021-09-07 07:52 UTC, treo commented on classifai-core/src/main/java/ai/classifai/util/message/ReplyHandler.java
> +    }
This is very similar to `sendEmptyResult`, Is there a reason why both of them are needed?

2021-09-07 07:58 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/router/V1Endpoint.java
> +                log.info("Failure in updating database for " + loader.getAnnotationType() + " project: " + loader.getProjectName());
Yeah. I realize this is just updating the value in db. And not returning any response. This is part of an api process. maybe they should be chained together.

2021-09-07 08:12 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/util/message/ReplyHandler.java
> +    }
The difference is sendEmptyResult does not return result, while this will.

2021-09-07 08:14 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
> +    }
Ahh yes. Thanks.

2021-09-07 09:37 UTC, ken479 approved these changes

2021-09-07 09:49 UTC, treo approved these changes
👍

2021-09-08 00:54 UTC, merged