♻️ Remove JsonObject from return value
CertifaiAI/classifai pull request #505
Opened 2021-09-15 02:38 UTC by devenyantis

# Description

Some return values are changed. Some remain as json object. Also added steps to handle fail cases to map the functionality of frontend.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (Non-breaking change which fixes an issue)
- [ ] New feature (Non-breaking change which adds functionality)
- [x] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

2021-09-15 10:54 UTC, treo requested changes
A few comments here. I've only put them on the first place I noticed something, even when it applies to multiple places.

2021-09-15 10:54 UTC, treo commented on classifai-core/src/main/java/ai/classifai/action/DeleteProjectData.java
> +    public static List<String> deleteProjectDataOnComplete(ProjectLoader loader, List<String> deleteUUIDList, JsonArray deletedDataPath) throws IOException {
While you are at it, please also replace all function parameters to not use any Json* type.

2021-09-15 10:54 UTC, treo commented on classifai-core/src/main/java/ai/classifai/action/DeleteProjectData.java
> +        return loader.getSanityUuidList();
This looks like it is the same outcome in any case, so you can just as well skip the return in the if.

2021-09-15 10:54 UTC, treo commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
>      }
If it isn't going to return anything, you don't need to have the future void return, do you?

2021-09-15 10:54 UTC, treo commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
> +    public Future<List<JsonObject>> getAllProjectsMeta(int annotationType) {
Try to not have any Json* types in the return types, even in the generics :)

2021-09-17 01:29 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/DeleteProjectData.java
> +        return loader.getSanityUuidList();
Noted

2021-09-17 06:18 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
>      }
@treo 
Still need to returns the future object that carry nothing.

2021-09-21 03:24 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
> +    public Future<List<JsonObject>> getAllProjectsMeta(int annotationType) {
Changed to dto

2021-09-21 15:07 UTC, treo requested changes
A few more comments. Again they apply in a few cases, but I didn't put them everywhere, as it is pretty obvious where the same pattern repeats.

2021-09-21 15:07 UTC, treo commented on classifai-core/src/main/java/ai/classifai/action/DeleteProjectData.java
> +        return loader.getSanityUuidList();
Can that error not happen anymore?

2021-09-21 15:07 UTC, treo commented on classifai-core/src/main/java/ai/classifai/action/ProjectExport.java
> +            file.write(new JsonObject(jsonString).encodePrettily());
That looks a bit weird. Why write the file to a json string, then reload it and then write it again? Just so it is pretty json? Is it ever going to by modified by hand?

2021-09-21 15:07 UTC, treo commented on classifai-core/src/main/java/ai/classifai/action/parser/PortfolioParser.java
> +
some cleanup may be necessary here

2021-09-21 15:07 UTC, treo commented on classifai-core/src/main/java/ai/classifai/action/parser/ProjectParser.java
> +            );
In this case, I think it makes sense to use a builder pattern, that way we know both what the columns mean and it is harder to mess the order up

2021-09-21 17:24 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/ProjectExport.java
> +            file.write(new JsonObject(jsonString).encodePrettily());
I'm following the original structure of config. Found another way to use pretty json without changing to jsonobject.

2021-09-21 17:32 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/DeleteProjectData.java
> +        return loader.getSanityUuidList();
It can. But before this, it returns jsonobject which is directly formatted for api response. Now, all the response format happens elsewhere.

2021-09-22 05:40 UTC, treo requested changes
I think you should be able to use the object mapper in a few more places to deserialize directly, instead of manually pulling data from a JsonObject or JsonArray

2021-09-22 05:40 UTC, treo commented on classifai-core/src/main/java/ai/classifai/action/parser/ProjectParser.java
> +    }
Wouldn't it be possible to use the object mapper for direct deserialization here?

2021-09-22 19:21 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/parser/ProjectParser.java
> +    }
Changed. Now using mapper readvalue and treenode

2021-09-23 12:42 UTC, treo requested changes

2021-09-23 12:42 UTC, treo commented on classifai-core/src/main/java/ai/classifai/action/parser/ProjectParser.java
> +        JsonArray versionListArray = new JsonArray(versionListString);
I was thinking more along the lines of `mp.readValue(versionListString, new TypeReference<List<VersionConfigProperties>>() {});`

Let the ObjectMapper do all the work. Or is the actual structure of the incoming json string different from the Java object you are trying to construct?

2021-09-24 03:11 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/parser/ProjectParser.java
> +        JsonArray versionListArray = new JsonArray(versionListString);
Oh wow. Didn't know about the typereference. Thanks

2021-09-24 05:52 UTC, treo requested changes

2021-09-24 05:52 UTC, treo commented on classifai-core/src/main/java/ai/classifai/util/collection/ConversionHandler.java
> +            return mp.readValue(versionListString, new TypeReference<>() {});
You are still meant to pass the actual type reference in the generic parameter here, otherwise it will not know what object it is supposed to create.

2021-09-27 00:43 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/util/collection/ConversionHandler.java
> +            return mp.readValue(versionListString, new TypeReference<>() {});
I thought it will infer from when it is used. No? because it worked with the right type.

2021-09-27 07:43 UTC, treo approved these changes

2021-09-27 07:49 UTC, merged