⚡  Improve Image loading speed into workspace
CertifaiAI/classifai pull request #506
Opened 2021-09-22 10:50 UTC by ken479

# Description

Improve image loading speed by reducing backend Image data processing through directly read from the Image file instead of through the byte array. 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (Non-breaking change which fixes an issue)
- [ ] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

2021-09-22 10:55 UTC, ken479 commented
> Kudos, SonarCloud Quality Gate passed!    ![Quality Gate passed](https://camo.githubusercontent.com/e4a90cf346b46d44c5652111d68603714bfb7693043d07a95992de3a30bfce04/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f7061737365642d313670782e706e67)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=CertifaiAI_classifai&pullRequest=506&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=CertifaiAI_classifai&pullRequest=506&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=CertifaiAI_classifai&pullRequest=506&resolved=false&types=BUG)
> [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=CertifaiAI_classifai&pullRequest=506&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=CertifaiAI_classifai&pullRequest=506&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=CertifaiAI_classifai&pullRequest=506&resolved=false&types=VULNERABILITY)
> [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=CertifaiAI_classifai&pullRequest=506&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=CertifaiAI_classifai&pullRequest=506&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=CertifaiAI_classifai&pullRequest=506&resolved=false&types=SECURITY_HOTSPOT)
> [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=CertifaiAI_classifai&pullRequest=506&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=CertifaiAI_classifai&pullRequest=506&resolved=false&types=CODE_SMELL) [1 Code Smell](https://sonarcloud.io/project/issues?id=CertifaiAI_classifai&pullRequest=506&resolved=false&types=CODE_SMELL)
> 
> [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=CertifaiAI_classifai&pullRequest=506) No Coverage information
> [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=CertifaiAI_classifai&pullRequest=506&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=CertifaiAI_classifai&pullRequest=506&metric=new_duplicated_lines_density&view=list)

rotateWithOrientation function is ignored because we want to maintain original image orientation during annotation. This function is stay for future use if needed

2021-09-23 02:50 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/data/type/image/WebpImageData.java
> +        return 0;
What does 0 means? Can make it class constant for readability.

2021-09-23 02:53 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
> +                imgData = ImageHandler.getThumbNailFromCloud(img);
I know this this cannot be tested as well. Can use the same function getThumbnail? because previously both reading (cloud and local are same)

2021-09-23 03:03 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
> +        int depth = Objects.requireNonNull(ImageData.getImageData(imageFile)).getDepth();
I think can reduce the calling of getImageData. Only call the method and check for null once. And only get the width, height and depth after that.

2021-09-23 03:03 UTC, devenyantis requested changes
Just some comments on few parts

2021-09-23 03:07 UTC, ken479 commented on classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
> +        int depth = Objects.requireNonNull(ImageData.getImageData(imageFile)).getDepth();
Good idea, I will change it

2021-09-23 03:07 UTC, ken479 commented on classifai-core/src/main/java/ai/classifai/data/type/image/WebpImageData.java
> +        return 0;
agree, i will include a constant in the class

2021-09-23 05:52 UTC, ken479 commented on classifai-core/src/main/java/ai/classifai/database/annotation/AnnotationVerticle.java
> +                imgData = ImageHandler.getThumbNailFromCloud(img);
Hi @devenyantis,  this will be taking further action when we work on wasabi. Will remain using that function first.

2021-09-23 09:07 UTC, devenyantis approved these changes

2021-09-23 09:07 UTC, merged