Api annotation
CertifaiAI/classifai pull request #507
Opened 2021-09-29 18:04 UTC by devenyantis

# Description

Applying Jax Rs api annotation.

Also removing the usage of `helper.checkIfDockerEnv(context);` .
This functionality cannot be tested since the docker build is not available currently. Does not interfere with the main functionality.

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (Non-breaking change which fixes an issue)
- [ ] New feature (Non-breaking change which adds functionality)
- [x] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

2021-09-30 11:12 UTC, treo requested changes
Not entirely sure if it works with this particular extension, but if I recall correctly, you should be able to put `@Produces` and `@Consumes` annotations on the class, so you don't have to put it on every public method. 

Otherwise, I've put a few more questions and suggestions as comments.

2021-09-30 11:12 UTC, treo commented on classifai-core/src/main/java/ai/classifai/action/parser/ProjectParser.java
> +            }
Why not push this error logging into the hash method itself?

2021-09-30 11:12 UTC, treo commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
> +            promise.fail(RenameDataErrorCode.FILENAME_CONTAIN_ILLEGAL_CHAR.toString());
Why the toString conversion?

2021-09-30 11:12 UTC, treo commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
> +            Integer fileSize = requestBody.getFileSizeParam();
If the variables aren't used anywhere, you might as well just directly set it, now that it isn't as complicated to get them from the request body

2021-09-30 11:12 UTC, treo commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
> +            }
Is this JsonArray conversion here really necessary?

2021-09-30 11:12 UTC, treo commented on classifai-core/src/main/java/ai/classifai/dto/api/reader/CreateProjectReader.java
> +public class CreateProjectReader implements ValueReader<CreateProjectBody> {
These readers look like they are very generic. I'd expect that it would be handled automatically. Is there a specific reason why you needed to create them?

2021-09-30 11:12 UTC, treo commented on classifai-core/src/main/java/ai/classifai/router/Util.java
>      }
This looks like it should probably just be inlined

2021-09-30 11:12 UTC, treo commented on classifai-core/src/main/java/ai/classifai/router/endpoint/DataEndpoint.java
> +    @RequestReader(DeleteProjectDataReader.class)
Why not `@Consumes(MediaType.APPLICATION_JSON)` here instead of the custom request reader?

2021-09-30 11:12 UTC, treo commented on classifai-core/src/main/java/ai/classifai/util/message/ReplyHandler.java
> +    @Getter private static final Integer FAILED = 0;
I'd make those constants public instead of putting a getter on them.

2021-09-30 16:13 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
> +            promise.fail(RenameDataErrorCode.FILENAME_CONTAIN_ILLEGAL_CHAR.toString());
Because promise.fail only accepts string. Other option is to return a throwable

2021-09-30 16:16 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
> +            Integer fileSize = requestBody.getFileSizeParam();
Changed

2021-10-01 01:24 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/router/Util.java
>      }
Yes. all the usage of this method is changed.

2021-10-01 01:30 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/router/endpoint/DataEndpoint.java
> +    @RequestReader(DeleteProjectDataReader.class)
Changed

2021-10-01 01:36 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
> +            promise.fail(RenameDataErrorCode.FILENAME_CONTAIN_ILLEGAL_CHAR.toString());
because promise.fail only accepts string

2021-10-01 04:03 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
> +            }
Changed to object

2021-10-01 06:02 UTC, treo requested changes
A few more nitpicks

2021-10-01 06:02 UTC, treo commented on classifai-core/src/main/java/ai/classifai/action/parser/ProjectParser.java
> +        ObjectMapper mp = new ObjectMapper();
You should be able to replace this entire method with something along the lines of the following:
```java
Map<String, AnnotationVersion> annotationDict = mp.readValue(jsonVersionList, new TypeReference<Map<String, AnnotationVersion>>{});
```

2021-10-01 06:02 UTC, treo commented on classifai-core/src/main/java/ai/classifai/database/versioning/AnnotationVersion.java
>  public class AnnotationVersion
How is this class different from DataInfoProperties? It looks like they could be merged into one thing.

2021-10-01 06:02 UTC, treo commented on classifai-core/src/main/java/ai/classifai/util/Hash.java
> +            log.info("Error getting hash. \n" + e);
don't use string concatenation here. By passing in the entire exception object, you get better logging.

2021-10-04 08:50 UTC, treo approved these changes

2021-10-04 08:59 UTC, merged