Remove static object
CertifaiAI/classifai pull request #508
Opened 2021-10-06 09:37 UTC by devenyantis

# Description

Remove static object and replace with constructor or getter/setter

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (Non-breaking change which fixes an issue)
- [ ] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [X] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [ ] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

2021-10-06 12:10 UTC, treo requested changes
There is still plenty of static object use left. 

In particular the `ProjectHandler` class is used all over the place in this static manner.

2021-10-06 12:10 UTC, treo commented on classifai-core/src/main/java/ai/classifai/MainVerticle.java
> +    private static final EndpointRouter serverVerticle = new EndpointRouter();
Do these need to be static at all?

2021-10-13 08:04 UTC, treo requested changes
Just a small nitpick. 

I also see that you've added a lot more project state transitions, shouldn't that happen within the projectExport object itself?

2021-10-13 08:04 UTC, treo commented on classifai-core/src/main/java/ai/classifai/action/parser/ProjectParser.java
> +            );
I think it makes sense to push the default values into the object definition and use `@Builder.Default` instead of having this disconnect.

2021-10-13 08:28 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/parser/ProjectParser.java
> +            );
Noted

2021-10-13 08:32 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/parser/ProjectParser.java
> +            );
For the project state transitions. 

No. It doesn't. When zipping the image, the current process run in separate thread which is the only way to mark as success. 

I also followed the original flow. Found out that I forgot to add the starting process status. Realize when testing this with bigger dataset.

2021-10-13 10:51 UTC, treo requested changes

2021-10-13 10:51 UTC, treo commented on classifai-core/src/main/java/ai/classifai/action/parser/ProjectParser.java
> +
I guess you forgot to remove this?

2021-10-13 11:07 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/parser/ProjectParser.java
> +
Oh noo. Ok. Thanks

2021-10-13 11:08 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/action/parser/ProjectParser.java
> +
Removed.

2021-10-13 12:14 UTC, treo approved these changes

2021-10-13 14:39 UTC, merged