✨  Image processing and project statistic
CertifaiAI/classifai pull request #514
Opened 2021-11-22 23:17 UTC by ken479

# Description

Include back image processing improvement and project statistic feature in the Classifai new backend

Please delete options that are not relevant.

- [ ] Bug fix (Non-breaking change which fixes an issue)
- [x] New feature (Non-breaking change which adds functionality)
- [ ] Breaking change (Fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update (Example: REST API changes)

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged
- [ ] CHANGELOG.md has been updated
- [ ] Update [Gitbook REST API Page](https://docs.classifai.ai/v/dev/development/rest-api)

2021-11-24 02:55 UTC, devenyantis requested changes

2021-11-24 02:55 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
> +        if (!projectPath.exists())
What happen to the ProjectStatisticResponse.builder if this happens? Will it trigger error?

2021-11-24 02:55 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
> +    private static int oriWidth = 0;
If this is immutable, it should be final. Otherwise, use non static

2021-11-24 02:55 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/util/data/LabelListHandler.java
> +    private static final List<List<JsonArray>> totalImage = new ArrayList<>();
This final type variable should be for immutable. Otherwise, should be non static and non final.

2021-11-24 02:55 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/util/data/LabelListHandler.java
> +    private static LinkedHashMap<String,JsonObject> getAnnotationData(String annotationDict)
Need to remove JsonObject. Use dto instead.

2021-11-24 02:55 UTC, devenyantis commented on classifai-core/src/main/java/ai/classifai/util/data/LabelListHandler.java
> +    private static JsonArray getAnnotationStatus(String annotationDictValue)
Same as this. Should use dto. Remove Jsonarray

2021-11-25 02:05 UTC, ken479 commented on classifai-core/src/main/java/ai/classifai/util/data/LabelListHandler.java
> +    private static JsonArray getAnnotationStatus(String annotationDictValue)
@devenyantis Have converted to list of dto properties

2021-11-25 02:06 UTC, ken479 commented on classifai-core/src/main/java/ai/classifai/util/data/LabelListHandler.java
> +    private static LinkedHashMap<String,JsonObject> getAnnotationData(String annotationDict)
@devenyantis converted to list of dto

2021-11-25 02:07 UTC, ken479 commented on classifai-core/src/main/java/ai/classifai/util/data/LabelListHandler.java
> +    private static final List<List<JsonArray>> totalImage = new ArrayList<>();
@devenyantis have made it as final type

2021-11-25 02:08 UTC, ken479 commented on classifai-core/src/main/java/ai/classifai/util/data/ImageHandler.java
> +    private static int oriWidth = 0;
@devenyantis remove field and introduce local variable

2021-11-25 02:22 UTC, ken479 commented on classifai-core/src/main/java/ai/classifai/database/portfolio/PortfolioDB.java
> +        if (!projectPath.exists())
@devenyantis it will trigger error of not getting the info of label list, and graph in front end is empty

2021-11-26 00:37 UTC, devenyantis approved these changes

2021-11-26 00:37 UTC, merged